language: php

php:
  - 5.6
  - 7
  - hhvm

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

before_script:
  - composer update $PREFER_LOWEST

script:
  - ./vendor/bin/phpunit
